---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-trigger-sa
  namespace: openhands-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipeline-runner
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines"]
    verbs: ["get", "list"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipeline-runner-binding
subjects:
  - kind: ServiceAccount
    name: pipeline-trigger-sa
    namespace: openhands-pipeline
roleRef:
  kind: Role
  name: tekton-pipeline-runner
  apiGroup: rbac.authorization.k8s.io
